// <auto-generated />
using System;
using HospitalSanVicente.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalSanVicente.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20251015000232_AddDoctorDocumentToAppointmentsDate")]
    partial class AddDoctorDocumentToAppointmentsDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HospitalSanVicente.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AppointmentDate");

                    b.Property<int>("DoctorDocument")
                        .HasColumnType("int")
                        .HasColumnName("DoctorId");

                    b.Property<int>("PatientDocument")
                        .HasColumnType("int")
                        .HasColumnName("PatientId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DoctorDocument");

                    b.HasIndex("PatientDocument");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HospitalSanVicente.Models.Doctor", b =>
                {
                    b.Property<int>("Document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("document");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Document"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("area");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.HasKey("Document");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalSanVicente.Models.Patient", b =>
                {
                    b.Property<int>("Document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("document");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Document"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("bloodType");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.HasKey("Document");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HospitalSanVicente.Models.Appointment", b =>
                {
                    b.HasOne("HospitalSanVicente.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorDocument")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalSanVicente.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientDocument")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSanVicente.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HospitalSanVicente.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
